/* BY SUBMITTING THIS FILE TO CARMEN, I CERTIFY THAT I HAVE PERFORMED ALL OF THE WORK TO CREATE THIS FILE AND/OR DETERMINE THE ANSWERS FOUND WITHIN THIS FILE MYSELF WITH NO ASSISTANCE FROM ANY PERSON (OTHER THAN THE INSTRUCTOR OR GRADERS OF THIS COURSE) AND I HAVE STRICTLY ADHERED TO THE TENURES OF THE OHIO STATE UNIVERSITY’S ACADEMIC INTEGRITY POLICY.
 */

#include "lab4.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

Node *findNodeID(Node *head, int ID){
	int StudentID = ID;
	Node *p = NULL;
	p = head;

	while(p!=NULL){
		if(StudentID==p->Student.student_ID){
			return p;
		}
		p = p->next;
	}
}
